---
baseURL: "/"
languageCode: en-us
Title: Latent Garden
theme:
  - hugo-video
  - lsc
disableKinds:
  - "taxonomy"
  - "term"
  - "sitemap"

markup:
  goldmark:
    renderer:
      unsafe: true

params:
    Author: Matúš Solčány
    Description: Latent Garden is the ongoing artistic data exploration project. The goal of the project is to develop intuitive ways to navigate latent spaces in the context of generative neural networks.   
    SiteURL: "https://latent.garden"
    email_encoded: "&#109;&#097;&#116;&#117;&#115;&#046;&#115;&#111;&#108;&#099;&#097;&#110;&#121;&#064;&#112;&#114;&#111;&#116;&#111;&#110;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;"
---


